version: "2"
services:
  common:
    image: dorothy-common
    build:
      context: .
      dockerfile: common.Dockerfile
  tui:
    image: dorothy-tui
    build:
      context: .
      dockerfile: tui.Dockerfile
  x11-gui:
    image: dorothy-x11-gui
    build:
      context: .
      dockerfile: x11-gui.Dockerfile
