version: "2"
services:
  tui:
    image: dorothy-tui
    build:
      context: .
      dockerfile: dorothy-tui.Dockerfile
  x11-gui:
    image: dorothy-x11-gui
    build:
      context: .
      dockerfile: dorothy-x11-gui.Dockerfile
